const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

const ACTIVE_USER_REQUEST = 'ACTIVE_USER_REQUEST'
const ACTIVE_USER_SUCCESS = 'ACTIVE_USER_SUCCESS'
const ACTIVE_USER_FAIL = 'ACTIVE_USER_FAIL'


const API_REQUEST = 'API_REQUEST'
const API_SUCCESS = 'API_SUCCESS'
const API_FAIL = 'API_FAIL'
const actionTypes = {
  USER_SIGNUP_REQUEST,
  USER_SIGNUP_SUCCESS,
  USER_SIGNUP_FAIL,

  ACTIVE_USER_REQUEST,
  ACTIVE_USER_SUCCESS,
  ACTIVE_USER_FAIL,


  API_REQUEST,
  API_SUCCESS,
  API_FAIL,
};

export default actionTypes;
